### ISSUE TITLE
Pushback test fails with bad_alloc if modified to use std::vector

### ISSUE THREAD

**Issue by mcordery** [moya-lang/Allocator#17]
Modified Measure.cpp to include a pushback test for std::vector

#include <vector>

    PushBackTest<std::vector<DataType>> pushBackVectorTestStl;
    PushBackTest<std::vector<DataType, MemoryPoolAllocator>> pushBackVectorTestFast;
    printTestStatus("Vector PushBack", pushBackVectorTestStl, pushBackVectorTestFast);

At run time this fails with

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by mcordery** [comment]
Also fails with clang++

**Comment by moya-mmoczala** [comment]
Vector doesn't need to be speed up as it already allocates a fixed amount of memory. The Allocator does not support such containers and it was intended by its design.
