### ISSUE TITLE
Reason for using `std::allocator<void>::const_pointer`

### ISSUE THREAD

**Issue by lambdaknight** [moya-lang/Allocator#3]
Is there a reason you use `std::allocator<void>::const_pointer` instead of just `const void*`? In C++17, `std::allocator<void>` is deprecated and it will be completely gone in C++20.

**Comment by moya-mmoczala** [comment]
Thank you for reporting. I'll correct it.

**Comment by moya-mmoczala** [comment]
Issue has been resolved
