### ISSUE TITLE
Vector???

### ISSUE THREAD

**Issue by shahramkom** [moya-lang/Allocator#8]
Why the vector is not on this list???

**Comment by moya-mmoczala** [comment]
Because the vector is working on different principle. If you know the max number of elements for the vector, you can reserve required memory by using `srd::vector::reserve()` function.

**Comment by yhyu13** [comment]
@moya-mmoczala I've tried to add a similar test case foe vector in measure.cpp and it actually failed at [here](https://github.com/moya-lang/Allocator/blob/697232e90ef5023914bad2073b65819a3ef43f2e/Allocator.h#L137), why is n has to be 1?

**Comment by moya-mmoczala** [comment]
Vector is a container that does not have list based implementation. Instead, it is like an array - a single and continuous block of memory. So, as in case of Moya Allocator, if you know the maximum size you will work with then you can pre-allocate a memory. In other words, vector already works similarly to Moya Allocator so there is no way to make it any faster.
